version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-katana-challenge
    restart: unless-stopped
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - NODE_PATH=/src
      - NODE_ENV=dev
    ports:
      - 3000:3000
    networks:
      vpcbr:
        ipv4_address: 10.5.0.2
    volumes:
      - ./src:/app/src
networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
